### ISSUE TITLE
Could you share the code about how you transfer frames to tfrecord?

### ISSUE THREAD

**Issue by gsygsy96** [SmartPorridge/google-AVA-Dataset-downloader#2]
I know it's unsuitable......I have tried to reproduct the baseline model for a long time.I tried with tensorflow object detection api  followed the advice offered by the author. But still having some bug,I think the problem lies in tfrecord. Could you share me with this part of this code?If it's convenient for you...

**Comment by SmartPorridge** [comment]
@shanYanGuan so sorry, I didn't  reproduce the baseline model. I only download the dataset and I will use it in the future....

**Comment by ShineeSheng** [comment]
The download link doesn't work. Could you share a link that can download the dataset. Preciate...
